export const POST_CREATE_EDU = "/edu-center"
export const POST_SIGNIN_EDU = "/edu-center/signin"

export const GET_EDU = "/edu-center"
export const GET_EDU_BY_ID = "/edu-center"
export const PATCH_UPDATE_EDU_BY_ID = "/edu-center"
export const DEL_EDUBY_ID = "/edu-center"
export const DEL_EDU_IMG_BY_ID = "/edu-center"

export const POST_TEACHER = "/teacher"
export const GET_TEACHER_BY_ID = "/teacher"
export const GET_TEACHER = "/teacher"
export const PATCH_UPDATE_TEACHER_BY_ID = "/teacher"
export const DEL_TEACHER_BY_ID = "/teacher"

export const POST_STUDENT = "/student"
export const GET_STUDENT = "/student"
export const GET_STUDENT_BY_ID = "/student"
export const PATCH_UPDATE_STUDENT = "/student"
export const DEL_STUDENT_BY_ID = "/student"
